plugins {
    id 'com.android.application'
}

android {
    namespace "com.micklab.whisper"
    compileSdk 35

    defaultConfig {
        applicationId "com.micklab.whisper"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
